// export const ADD_INGREDIENT = 'ADD_INGREDIENT';
// export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
// export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_SEMESTERS = 'SET_SEMESTERS';
export const SELECT_SEMESTER = 'SELECT_SEMESTER'