// export const ADD_INGREDIENT = 'ADD_INGREDIENT';
// export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
// export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_LOADING = 'SET_LOADING';
export const SET_SEMESTERS = 'SET_SEMESTERS';
export const SELECT_SEMESTER = 'SELECT_SEMESTER';
export const SET_INIT_DATA = 'SET_INIT_DATA';
export const UPDATE_COURSE_TYPE = 'UPDATE_COURSE_TYPE';
export const UPDATE_BRANCH = 'UPDATE_BRANCH';
export const UPDATE_CREDITS = 'UPDATE_CREDITS';


