
export const SET_LOADING = 'SET_LOADING';
export const SET_SEMESTERS = 'SET_SEMESTERS';
export const SELECT_SEMESTER = 'SELECT_SEMESTER';
export const SET_INIT_DATA = 'SET_INIT_DATA';
export const UPDATE_COURSE_TYPE = 'UPDATE_COURSE_TYPE';
export const UPDATE_BRANCH = 'UPDATE_BRANCH';
export const UPDATE_CREDITS = 'UPDATE_CREDITS';
export const UPDATE_CLASH = 'UPDATE_CLASH';
export const SET_FILTERED_COURSE_LIST = 'SET_FILTERED_COURSE_LIST';
export const SET_SELECTED_COURSE = 'SET_SELECTED_COURSE';
export const ADD_SELECTED_COURSE = 'ADD_SELECTED_COURSE';
export const REMOVE_SELECTED_COURSE = 'REMOVE_SELECTED_COURSE';
export const SET_SCHED_BITMAP = 'SET_SCHED_BITMAP';




